services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      -   "8876:80"
    depends_on:
      -   app
    container_name: nginx-test
    networks:
      - test

  app:
      build:
          context: .
          dockerfile: _docker/app/Dockerfile
      volumes:
          - ./:/var/www
      ports:
          - "5173:5173"
      extra_hosts:
          - "host.docker.internal:host-gateway"
      depends_on:
          - db
          - meilisearch
          - redis
      container_name: app-test
      networks:
          - test

  db:
    image: mysql:8.0
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      -   ./tmp/db:/var/lib/mysql
    container_name: mysql-test
    networks:
      - test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    container_name: phpmyadmin-test
    networks:
      - test

  meilisearch:
    image: getmeili/meilisearch:v1.16
    environment:
        MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
        - meilidata:/meilidata
    ports:
        - "7700:7700"
    container_name: meilisearch-test
    networks:
        - test

  redis:
      image: redis:7-alpine
      container_name: redis-test
      volumes:
          - redisdata:/data
      command: redis-server --appendonly yes
      networks:
          - test

  redisinsight:
      image: redis/redisinsight:latest
      container_name: redisinsight-test
      ports:
          - "5540:5540"
      depends_on:
          - redis
      networks:
          - test

networks:
   test:
    driver: bridge

volumes:
    meilidata:
    redisdata:
